title: Ludovico Gorrieri's Homepage
page-top-title: Ludovico Gorrieri
top-section-bg-text: AI Engineer
home-subtitle: User Name&ensp;|&ensp;Ludovico Gorrieri
copyright-text: '&copy; Ludovico Gorrieri 2023-2026. All Rights Reserved.'
